<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>		
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="QuestPDF" Version="2026.5.0" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.8" />
		<PackageReference Include="ZXing.Net" Version="0.16.11" />
		<PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
	</ItemGroup>
</Project>
